// 弹框发布订阅key
export const ASYNC_SUBSCRIBE_MODAL = 'ASYNC_SUBSCRIBE_MODAL'
// 上传文件 key
export const ASYNC_SUBSCRIBE_UPLOAD_MODAL = 'ASYNC_SUBSCRIBE_UPLOAD_MODAL'
// 保存为数据集
export const ASYNC_SUBSCRIBE_SAVE_DATA_SET_MODAL = 'ASYNC_SUBSCRIBE_SAVE_DATA_SET_MODAL'
