// 基础信息
export const ASYNC_SUBSCRIBE_BASE_INFO_MODAL = 'ASYNC_SUBSCRIBE_BASE_INFO_MODAL'
// 参数配置
export const ASYNC_SUBSCRIBE_PARAM_INFO_MODAL = 'ASYNC_SUBSCRIBE_PARAM_INFO_MODAL'

// 上传特信文件
export const ASYNC_SUBSCRIBE_CHARACTER_FILE_MODAL = 'ASYNC_SUBSCRIBE_CHARACTER_FILE_MODAL'
