// 算法类型
export const CODE_TYPE_ENUM = {
	XIE_TONG: 'XIE_TONG',
	DM_XH_SC: 'DM_XH_SC',
	BO_XING_JIE_BIAN: 'BO_XING_JIE_BIAN',
	DUO_CHU_LI_YU: 'DUO_CHU_LI_YU',
	GU_DING_MU_BIAO: 'GU_DING_MU_BIAO',
	DDHWJC_MU_BIAO_GJBW_SB: 'DDHWJC_MU_BIAO_GJBW_SB',
	DDHWFJ_MU_BIAO: 'DDHWFJ_MU_BIAO',
	SAR_KJG_MU_BIAO: 'SAR_KJG_MU_BIAO',
	XT_RZ_ZC: 'XT_RZ_ZC',
	XT_GR_JC: 'XT_GR_JC'
}
