// 创建/编辑弹框发布订阅key
export const ASYNC_SUBSCRIBE_MODAL = 'ASYNC_SUBSCRIBE_MODAL'

// 版本弹框
export const ASYNC_SUBSCRIBE_VERSION_MODAL = 'ASYNC_SUBSCRIBE_VERSION_MODAL'
export const ASYNC_SUBSCRIBE_UPDATE_MODAL = 'ASYNC_SUBSCRIBE_UPDATE_MODAL'
